name: Count CPP Files and Update README (STARTCOUNT and ENDCOUNT)

on:
  push:
    branches:
      - main

jobs:
  count_cpp_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count CPP Files
        id: count_cpp_files
        run: |
          echo "$(find . -name '*.cpp' | wc -l)" > count.txt

          start_line=$(grep -n "STARTCOUNT" README.md | cut -d: -f1)
          end_line=$(grep -n "ENDCOUNT" README.md | cut -d: -f1)

          sed -i "${start_line}s/.*/STARTCOUNT/" README.md
          sed -i "${end_line}s/.*/ENDCOUNT/" README.md
          sed -i "${start_line}r count.txt" README.md
          rm count.txt

      - name: Update README
        run: |
          git commit -am "Update README with CPP file count"
          git push
