name: Count CPP Files and Update README (STARTCOUNT and ENDCOUNT)

on:
  push:
    branches:
      - main

jobs:
  count_cpp_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count CPP Files
        id: count_cpp_files
        run: |
          $count = find . -name "*.cpp" | wc -l
          $start = $(grep -n "STARTCOUNT" README.md | cut -d: -f1)
          $end = $(grep -n "ENDCOUNT" README.md | cut -d: -f1)

          sed -i "${start},${end}d" README.md
          sed -i "${start}i $count" README.md

      - name: Update README
        run: |
          git commit -am "Update README with new count"
          git push
