name: Count CPP Files

on:
  push:
    branches:
      - main  # Change this if you're using a different main branch name

jobs:
  count_cpp_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Count CPP Files
      id: count
      run: |
        count=$(find . -type f -name "*.cpp" | wc -l)
        echo "::set-output name=cpp_count::$count"

    - name: Update README
      run: |
        sed -i -e "s/<!--- STARTCOUNT --->.*<!--- ENDCOUNT --->/<!--- STARTCOUNT --->$(( $(cat README.md | grep -oP '(?<=<!--- STARTCOUNT --->).*?(?=<!--- ENDCOUNT --->)' | tr -d '[:space:]') + ${{ steps.count.outputs.cpp_count }} ))<!--- ENDCOUNT --->/" README.md
