name: Count CPP Files and Update README (STARTCOUNT and ENDCOUNT)

on:
  push:
    branches:
      - main

jobs:
  count_cpp_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count CPP Files
        id: count_cpp_files
        run: |
          echo "CPP Files: $(find . -name '*.cpp' | wc -l)" >> README.md
          echo "H Files: $(find . -name '*.h' | wc -l)" >> README.md
          echo "Total Files: $(find . -name '*.cpp' -o -name '*.h' | wc -l)" >> README.md

      - name: Update README
        run: |
          sed -i '/STARTCOUNT/,/ENDCOUNT/c\STARTCOUNT\nCPP Files: $(find . -name '*.cpp' | wc -l)\nH Files: $(find . -name '*.h' | wc -l)\nTotal Files: $(find . -name '*.cpp' -o -name '*.h' | wc -l)\nENDCOUNT' README.md
